#!/usr/bin/env python3
"""Generate STATUS.md - the phase-wise board - from the task files.

STATUS.md is the one place that answers "what is done, what is pending, what is
blocked, what is open", and it is generated so it cannot drift from the task files
the way the hand-maintained Orchestration.md status boards did.

There is deliberately no separate BLOCKERS.md: a blocker means nothing without the
phase it stops, so open items are rendered inside the phase that owns them, plus one
cross-phase table at the top for "what is stopping work right now".

    python tools/build_status.py            # write STATUS.md
    python tools/build_status.py --check    # exit 1 if STATUS.md is stale (CI)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fwtasks as F  # noqa: E402

OUT = 'STATUS.md'
ORDER = ['done', 'in-review', 'in-progress', 'blocked', 'not-started', 'cancelled']
MARK = {'done': '✅ done', 'in-review': '🔵 in-review', 'in-progress': '🟡 in-progress',
        'blocked': '⛔ blocked', 'not-started': '⬜ not-started', 'cancelled': '⊘ cancelled'}


def esc(s):
    return (s or '').replace('|', '\\|').strip()


def rel_link(from_dir, target):
    """Markdown link from the repo root file STATUS.md."""
    return target


def pct(tasks):
    """Percent complete by TASK COUNT, never by hours.

    STATUS.md must not publish an hours total. `[CE]` (CapacityAndEffortModel) is the
    hours model of record, and a total derived here would be a second, contradicting
    figure - the exact defect this restructure exists to remove. Per-task `h` is still
    shown, but it is quoted from the story card, not summed into a new claim.
    """
    live = [t for t in tasks if t.get('status') != 'cancelled']
    if not live:
        return 0
    return round(100.0 * sum(1 for t in live if t.get('status') == 'done') / len(live))


def build():
    tasks = F.load_tasks()
    phases = F.load_phases()
    reg = F.load_registers()

    # ---- group by (mvp, phase) -------------------------------------------------
    groups = {}
    for t in tasks:
        groups.setdefault((t.get('mvp', '1'), t.get('phase', '')), []).append(t)

    def gkey(k):
        return (str(k[0]), F.phase_sort_key(k[1]))

    L = []
    L.append('# Flat Wire — Delivery Status')
    L.append('')
    L.append('> ⚙ **Generated by `tools/build_status.py` from the task files — DO NOT EDIT BY HAND.**')
    L.append('> Every value here comes from the `status:` / `owner:` front-matter of a file in')
    L.append('> `*/tasks/`. To change something on this page, change it in the task file and re-run.')
    L.append('')

    # ---- at a glance -----------------------------------------------------------
    L.append('## At a glance')
    L.append('')
    L.append('| MVP | Phase | Tasks | ✅ Done | 🔵 Review | 🟡 WIP | ⛔ Blocked | ⬜ Not started | % | Open items |')
    L.append('|---|---|---:|---:|---:|---:|---:|---:|---:|---|')
    tot = {s: 0 for s in ORDER}
    for k in sorted(groups, key=gkey):
        g = groups[k]
        c = {s: sum(1 for t in g if t.get('status') == s) for s in ORDER}
        for s in ORDER:
            tot[s] += c[s]
        opens = sorted({b for t in g for b in t.get('blocked_by', [])
                        if reg.get(b, {}).get('open', True)})
        title = phases.get(str(k[1]).upper(), {}).get('title', '')
        label = ('%s %s' % (k[1], title)).strip() or '(no phase)'
        L.append('| %s | %s | %d | %d | %d | %d | %d | %d | %d %% | %s |' % (
            k[0], esc(label[:44]), len(g), c['done'], c['in-review'], c['in-progress'],
            c['blocked'], c['not-started'], pct(g),
            ' · '.join(opens[:4]) + (' …' if len(opens) > 4 else '') if opens else '—'))
    L.append('| **All** | | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d %%** | |' % (
        len(tasks), tot['done'], tot['in-review'], tot['in-progress'],
        tot['blocked'], tot['not-started'], pct(tasks)))
    L.append('')
    L.append('*Percentages are by task count. **Hours are not totalled here** - '
             '[`CapacityAndEffortModel.md`](MVP-1/ProjectPlan/Development/CapacityAndEffortModel.md) '
             '`[CE]` is the hours model of record, and a total derived on this page would be a '
             'second figure to disagree with it.*')
    L.append('')
    if tot['cancelled']:
        L.append('*%d cancelled task(s) are listed in their phase but excluded from the %% figures.*'
                 % tot['cancelled'])
        L.append('')

    # ---- what is stopping work now --------------------------------------------
    blocking = {}
    for t in tasks:
        if t.get('status') == 'cancelled':
            continue
        for b in t.get('blocked_by', []):
            if reg.get(b, {}).get('open', True):
                blocking.setdefault(b, []).append(t)
    L.append('## ⛔ Stopping work right now')
    L.append('')
    if not blocking:
        L.append('*Nothing open is currently cited as a blocker.*')
    else:
        L.append('Open register items cited by at least one live task, most-blocking first.')
        L.append('')
        L.append('| Item | What | Blocks | Phases | Owner | Register |')
        L.append('|---|---|---|---|---|---|')
        for b in sorted(blocking, key=lambda x: (-len(blocking[x]), x)):
            ts = blocking[b]
            info = reg.get(b)
            ph = sorted({t.get('phase', '') for t in ts}, key=F.phase_sort_key)
            ids = ', '.join(t['id'] for t in ts[:6]) + (' …' if len(ts) > 6 else '')
            if info is None:
                what, owner, home = '**⚠ id not found in any register**', '', '—'
            else:
                what, owner, home = esc(info['text']), esc(info['owner']), os.path.basename(info['home'])
            L.append('| `%s` | %s | %s | %s | %s | %s |' % (
                b, what[:90], ids, ', '.join(ph), owner or '—', home))
    L.append('')

    # ---- per phase -------------------------------------------------------------
    L.append('---')
    L.append('')
    for k in sorted(groups, key=gkey):
        g = groups[k]
        title = phases.get(str(k[1]).upper(), {}).get('title', '')
        ppath = phases.get(str(k[1]).upper(), {}).get('path')
        c = {s: sum(1 for t in g if t.get('status') == s) for s in ORDER}
        L.append('## MVP-%s › Phase %s — %s' % (k[0], k[1] or '?', title or '(unmapped)'))
        L.append('')
        bits = ['%d task%s' % (len(g), '' if len(g) == 1 else 's'), '%d %% done' % pct(g)]
        L.append('**%s**' % ' · '.join(bits))
        if ppath:
            L.append('  · **Spec:** [%s](%s)' % (os.path.basename(ppath), ppath))
        L.append('')
        L.append('| Task | Title | Status | Owner | Stream | h | Sprint | Depends on | Blocked by |')
        L.append('|---|---|---|---|---|---:|---|---|---|')
        done_ids = {t['id'] for t in tasks if t.get('status') == 'done'}
        for t in sorted(g, key=lambda x: F.phase_sort_key(x.get('phase', '')) + (x['id'],)):
            deps = ' '.join(('%s✅' % d) if d in done_ids else d for d in t.get('depends_on', []))
            blk = ' '.join('**%s**' % b for b in t.get('blocked_by', [])
                           if reg.get(b, {}).get('open', True))
            flag = ''
            if t.get('status') == 'blocked' and not blk:
                flag = ' ⚠ *blocker closed — needs status update*'
            if t.get('status_confirmed') == 'false':
                flag += ' ⚠ *status inferred, unconfirmed*'
            L.append('| [%s](%s) | %s | %s%s | %s | %s | %s | %s | %s | %s |' % (
                t['id'], t['path'], esc(t.get('title', ''))[:64],
                MARK.get(t.get('status'), t.get('status', '')), flag,
                t.get('owner') or '—', '·'.join(t.get('streams', [])) or '—',
                t.get('hours', ''), t.get('sprint') or '—', deps or '—', blk or '—'))
        L.append('')

        opens = sorted({b for t in g for b in t.get('blocked_by', [])
                        if reg.get(b, {}).get('open', True)})
        if opens:
            L.append('**Open items owned by this phase**')
            L.append('')
            L.append('| Id | What | Blocks | Owner |')
            L.append('|---|---|---|---|')
            for b in opens:
                info = reg.get(b)
                ids = ', '.join(t['id'] for t in g if b in t.get('blocked_by', []))
                if info is None:
                    L.append('| `%s` | **⚠ id not found in any register** | %s | — |' % (b, ids))
                else:
                    L.append('| `%s` | %s | %s | %s |' % (
                        b, esc(info['text'])[:100], ids, esc(info['owner']) or '—'))
            L.append('')

        ready = [t for t in g
                 if t.get('status') == 'not-started'
                 and all(d in done_ids for d in t.get('depends_on', []))
                 and not [b for b in t.get('blocked_by', []) if reg.get(b, {}).get('open', True)]]
        L.append('**▶ Ready to start now:** %s'
                 % (', '.join('`%s`' % t['id'] for t in ready) if ready
                    else '*none — every not-started task here is waiting on a dependency or a blocker*'))
        L.append('')

    return '\n'.join(L) + '\n'


def main():
    body = build()
    path = os.path.join(F.ROOT, OUT)
    if '--check' in sys.argv:
        cur = F.read(OUT)
        if cur != body:
            print('build_status: STATUS.md is STALE - re-run tools/build_status.py')
            return 1
        print('build_status: STATUS.md is current')
        return 0
    tmp = path + '.tmp'
    with open(tmp, 'w', encoding='utf-8', newline='') as fh:
        fh.write(body)
    os.replace(tmp, path)
    print('build_status: wrote %s (%d lines)' % (OUT, body.count('\n')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
