#!/usr/bin/env python3
"""Generate FEATURES.md - the category board - and each parent's activity table.

STATUS.md answers "where are we by phase". FEATURES.md answers "where are we by
feature". Both are generated, and while the task files still exist both derive
from the same `status:` fields, so they cannot disagree.

The unit on this board is the ACTIVITY, not the category. That is deliberate: a
category inherits the UNION of its stories' blockers, so a category-level board
would show almost every row permanently blocked and "what can I start today"
would stop working. Activities keep the original granularity, so the readiness
calculation and the blocker fan-out ranking survive the collapse from 204 files
to 20.

Each parent's activity table lives inside its marker block and has two sources,
switched automatically:

  * while the task files exist, it is REGENERATED from them via the consolidation
    map - authoritative, and nothing is hand-typed;
  * once they are deleted, there is nothing left to derive from, so the tool
    PARSES the block it wrote last and rolls that up instead. From that point the
    table is hand-maintained and is the single writable record of status.

    python tools/build_features.py            # write FEATURES.md and the blocks
    python tools/build_features.py --check    # exit 1 if either is stale (CI)
    python tools/build_features.py --selftest # assert the activity table round-trips
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fwtasks as F  # noqa: E402
import build_consolidation_map as M  # noqa: E402

OUT = 'FEATURES.md'
FEATURE_DIR = '10-requirements/features'
BEGIN = '<!-- BEGIN GENERATED: absorbed-stories -->'
END = '<!-- END GENERATED: absorbed-stories -->'
BEGIN_BLK = '<!-- BEGIN GENERATED: blockers -->'
END_BLK = '<!-- END GENERATED: blockers -->'

ORDER = ['done', 'in-review', 'in-progress', 'blocked', 'not-started', 'cancelled']
MARK = {'done': '✅ done', 'in-review': '🔵 in-review', 'in-progress': '🟡 in-progress',
        'blocked': '⛔ blocked', 'not-started': '⬜ not-started', 'cancelled': '⊘ cancelled'}

RE_FRONT = re.compile(r'^---\r?\n(.*?)\r?\n---\r?\n', re.S)


def esc(s):
    return (s or '').replace('|', r'\|').strip()


def load_features():
    """[(id, front, path, filename)] for every FS-##-*.md, in id order."""
    out = []
    d = os.path.join(F.ROOT, FEATURE_DIR)
    if not os.path.isdir(d):
        return out
    for fn in sorted(os.listdir(d)):
        if not re.match(r'^FS-\d+-[a-z0-9-]+\.md$', fn):
            continue
        rel = FEATURE_DIR + '/' + fn
        m = RE_FRONT.match(F.read(rel))
        if not m:
            print('build_features: WARNING - %s has no parsable front-matter, skipped' % rel)
            continue
        front = F.parse_front(m.group(1))
        out.append((front.get('id', ''), front, rel, fn))
    return sorted(out, key=lambda x: x[0])


def pct(rows):
    live = [r for r in rows if r['status'] != 'cancelled']
    if not live:
        return 0
    return round(100.0 * sum(1 for r in live if r['status'] == 'done') / len(live))


def activities_from_tasks(tasks_by_cat, cid):
    """Seed one activity per absorbed story - the 1:1 starting point."""
    rows = []
    for t in tasks_by_cat.get(cid, []):
        rows.append({
            'ref': t['id'],
            'name': t.get('title', ''),
            'streams': t.get('streams') or ([t['stream']] if t.get('stream') else []),
            'status': t.get('status', ''),
            'depends_on': t.get('depends_on', []),
            'blocked_by': t.get('blocked_by', []),
            'evidence': t.get('status_note', ''),
            'unconfirmed': t.get('status_confirmed') == 'false',
        })
    return rows


# The activity-block parser is canonical in fwtasks, so stamp_trial_status.py and
# anything else that needs status after the task files are retired shares it.
activities_from_block = F.parse_activity_block


def render_block(rows, cid, derived, expected):
    """expected: how many stories the map says this category absorbed.

    0 means the category holds no story BY DESIGN. Without that distinction the
    banner told two by-design-empty categories that their task files "have been
    retired", which had never been true of either.
    """
    L = [BEGIN, '']
    if expected == 0:
        L += ['*No story maps here. This category is authored from specifications and '
              'registers, not from the backlog - see `[SCM §2.3]`.*', '', END]
        return "\n".join(L)
    if derived:
        L.append('> ⚙ **Generated by `tools/build_features.py` from the absorbed task files.** '
                 'Do not edit inside the markers.')
    else:
        L.append('> ⚙ **Written by `tools/build_features.py`, now hand-maintained** — the task '
                 'files it derived from have been retired, so this table is the single writable '
                 'record of status for this category. Keep the columns exactly as they are; '
                 '`--check` and `FEATURES.md` both parse them.')
    L.append('')
    if not rows:
        L.append('*No story maps here. This category is authored from specifications and '
                 'registers, not from the backlog.*')
        L.append('')
        L.append(END)
        return '\n'.join(L)
    L.append('**%d absorbed stor%s**, seeded one activity each. **Activities are expected to '
             'merge downward** as work proceeds — `FW-N17`/`N18`/`N19` are one rename, not '
             'three.' % (len(rows), 'y' if len(rows) == 1 else 'ies'))
    L.append('')
    L.append('| Ref | Activity | Streams | Status | Depends on | Blocked by |')
    L.append('|---|---|---|---|---|---|')
    for r in rows:
        flag = ' ⚠ *inferred*' if r.get('unconfirmed') else ''
        L.append('| `%s` | %s | %s | %s%s | %s | %s |' % (
            r['ref'], esc(r['name'])[:66], '·'.join(r['streams']) or '—',
            MARK.get(r['status'], r['status']), flag,
            ' '.join(r['depends_on']) or '—',
            ' '.join('**%s**' % b for b in r['blocked_by']) or '—'))
    L += render_evidence(rows)
    L.append('')
    L.append(END)
    return '\n'.join(L)


# Statuses whose work is finished or nearly so, and whose measured result is the
# only durable record that it was proven.
EVIDENCED = ('done', 'in-review')


def render_evidence(rows):
    """A generated record of what was BUILT and how it was verified.

    Step 9 archives the build records to 95-archive/, which this repository's own
    rules make non-citable. The measured verification in each plan's status_note
    is the only evidence that the work was proven, so it is lifted here while the
    plans are still live rather than after they are not.
    """
    done = [r for r in rows if r['status'] in EVIDENCED and r.get('evidence')]
    if not done:
        return []
    L = ['', '**Verification evidence for completed work.** Lifted from each build record '
         'before it is archived - `95-archive/` is not citable, so this is the durable copy.', '']
    L.append('| Ref | Status | Measured result |')
    L.append('|---|---|---|')
    for r in done:
        L.append('| `%s` | %s | %s |'
                 % (r['ref'], MARK.get(r['status'], r['status']), esc(r['evidence'])[:230]))
    return L


def render_blockers(rows, reg):
    """The blocker roll-up, GENERATED.

    An earlier pass hand-typed this table in four parents and got the "Blocks"
    column wrong in three of them - naming stories blocked by a different item,
    and naming stories belonging to another category. It is derived data, so it
    is now derived.
    """
    L = [BEGIN_BLK, '']
    hits = {}
    for r in rows:
        for b in r['blocked_by']:
            hits.setdefault(b, []).append(r['ref'])
    if not hits:
        L += ['*No activity in this category cites a blocker.*', '', END_BLK]
        return '\n'.join(L)
    unknown = [b for b in hits if b not in reg and F.canon(b) not in reg]
    # An unknown id must not be counted as open: reg.get(...).get('open', True)
    # defaults to True, which would report a retired prefix as a live blocker.
    live = [b for b in hits if b not in unknown
            and (reg.get(b) or reg.get(F.canon(b)) or {}).get('open', True)]
    closed = [b for b in hits if b not in unknown and b not in live]
    L.append('> \u2699 **Generated by `tools/build_features.py`.** Do not edit inside the markers '
             '- the union of `blocked_by:` across this category, which exists in no other '
             'document.')
    L.append('')
    parts = ['**%d open**' % len(live)]
    if closed:
        parts.append('%d closed but still cited' % len(closed))
    if unknown:
        parts.append('**%d resolving to no register** (`G61`)' % len(unknown))
    L.append('**%d register item%s cited by %d of %d activities** - %s.'
             % (len(hits), '' if len(hits) == 1 else 's',
                len({r for v in hits.values() for r in v}), len(rows), ', '.join(parts)))
    L.append('')
    L.append('| Item | State | Blocks | What is missing |')
    L.append('|---|---|---|---|')
    for b in sorted(hits, key=lambda x: (-len(hits[x]), x)):
        info = reg.get(b) or reg.get(F.canon(b))
        if info is None:
            state = '\u26a0 no register'
            what = ('**Retired prefix resolving to nothing** - needs retargeting or '
                    'removal (`G61`)')
        elif info['open']:
            state, what = '\u26d4 open', esc(info['text'])[:150]
        else:
            state = '\u2705 closed'
            what = '%s \u2014 \u26a0 still cited here' % esc(info['text'])[:120]
        L.append('| **`%s`** | %s | %s | %s |'
                 % (b, state, ' \u00b7 '.join('`%s`' % r for r in hits[b]), what))
    L.append('')
    L.append(END_BLK)
    return '\n'.join(L)

# Authored size, EXCLUDING the generated block. Measuring the whole file would be
# measuring how many stories a category absorbed, which is not a property the
# author controls. The risk this proxies for is a parent restating its phase
# specification, and prose has no checker - so it is reported, every run.
SIZE_TARGET = 12 * 1024
SIZE_LIMIT = 14 * 1024


def authored_bytes(rel):
    """File size less EVERY generated block - there are two, not one.

    Counting the blocker roll-up as authored prose would penalise exactly the
    categories whose roll-up is most useful.
    """
    text = F.read(rel)
    n = len(text)
    for begin, end in ((BEGIN, END), (BEGIN_BLK, END_BLK)):
        if begin in text and end in text:
            n -= len(text.split(begin, 1)[1].split(end, 1)[0])
    return n


def report_sizes(feats):
    over = []
    for cid, _front, rel, fn in feats:
        n = authored_bytes(rel)
        if n > SIZE_LIMIT:
            over.append((cid, n))
    if over:
        # ASCII only: every other tool here prints ASCII to stdout, and a Windows
        # cp1252 console raises UnicodeEncodeError on anything else - which would
        # crash this tool at exactly the moment the warning matters.
        print('  ! authored content over %d KB - check whether the phase specification is '
              'being restated rather than cited:' % (SIZE_LIMIT // 1024))
        for cid, n in over:
            print('      %s  %.1f KB' % (cid, n / 1024.0))


def build():
    feats = load_features()
    if not feats:
        print('build_features: no FS-## files found in %s' % FEATURE_DIR)
        return None, None
    tasks = F.load_tasks()
    reg = F.load_registers()

    by_cat = {}
    for t in tasks:
        cat = M.categorise(t)[0]
        if cat:
            by_cat.setdefault(cat, []).append(t)
    # What the MAP says each category absorbed. Read from the map rather than the
    # task files so it still answers correctly once the files are retired.
    expected = dict(M.read_expected_counts())
    # A silently-wrong expected count makes a populated category render as
    # "no story maps here", which is how two of them lost their activity table.
    # The map's own summary must cover every category and sum to the task count.
    if expected:
        miss = [c for c in M.CATEGORIES if c not in expected]
        if miss:
            print('build_features: REFUSING - the map summary has no row for %s' % miss)
            return None, None
        if tasks and sum(expected.values()) != len(tasks):
            print('build_features: REFUSING - map summary sums to %d, task files number %d'
                  % (sum(expected.values()), len(tasks)))
            return None, None

    # Per category: derive from task files while they exist, else parse the block.
    acts, derived_from_tasks = {}, {}
    for cid, front, rel, fn in feats:
        if by_cat.get(cid):
            acts[cid] = activities_from_tasks(by_cat, cid)
            derived_from_tasks[cid] = True
        else:
            parsed = activities_from_block(F.read(rel))
            acts[cid] = parsed
            derived_from_tasks[cid] = False

    all_rows = [r for cid, _f, _p, _n in feats for r in acts[cid]]
    done_refs = {r['ref'] for r in all_rows if r['status'] == 'done'}

    def open_blockers(rows):
        return sorted({b for r in rows for b in r['blocked_by']
                       if reg.get(b, {}).get('open', True)})

    L = ['# Flat Wire — Feature Status', '']
    L.append('> ⚙ **Generated by `tools/build_features.py` — DO NOT EDIT BY HAND.**')
    L.append('> The unit here is the **activity**, not the category: a category inherits the '
             'union of')
    L.append('> its stories\' blockers, so a category-level board would read as permanently '
             'blocked.')
    L.append('>')
    L.append('> [`STATUS.md`](STATUS.md) answers *where are we by phase*. This answers *where '
             'are we by feature*.')
    L.append('> Category definitions: [`10-requirements/features/`](10-requirements/features/README.md). '
             'Membership: [`[SCM §2.3]`](90-registers/StoryConsolidationMap.md).')
    L.append('')
    L.append('## At a glance')
    L.append('')
    L.append('| Category | Activities | ✅ | 🔵 | 🟡 | ⛔ | ⬜ | % | Open items |')
    L.append('|---|---:|---:|---:|---:|---:|---:|---:|---|')
    tot = {s: 0 for s in ORDER}
    for cid, front, rel, fn in feats:
        rows = acts[cid]
        c = {s: sum(1 for r in rows if r['status'] == s) for s in ORDER}
        for s in ORDER:
            tot[s] += c[s]
        ob = open_blockers(rows)
        L.append('| [%s %s](%s) | %d | %d | %d | %d | %d | %d | %d %% | %s |' % (
            cid, esc(front.get('title', ''))[:46], rel, len(rows),
            c['done'], c['in-review'], c['in-progress'], c['blocked'], c['not-started'],
            pct(rows), ' · '.join(ob[:3]) + (' …' if len(ob) > 3 else '') if ob else '—'))
    L.append('| **All** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d %%** | |' % (
        len(all_rows), tot['done'], tot['in-review'], tot['in-progress'],
        tot['blocked'], tot['not-started'], pct(all_rows)))
    L.append('')
    L.append('*Percentages are by activity count. **Hours are not totalled here** — '
             '[`CapacityAndEffortModel.md`](60-delivery/CapacityAndEffortModel.md) `[CE]` is the '
             'hours model of record, and no figure derived on this page would agree with it.*')
    L.append('')

    blocking = {}
    for r in all_rows:
        if r['status'] == 'cancelled':
            continue
        for b in r['blocked_by']:
            if reg.get(b, {}).get('open', True):
                blocking.setdefault(b, []).append(r)
    L.append('## ⛔ Stopping work right now')
    L.append('')
    if not blocking:
        L.append('*Nothing open is currently cited as a blocker.*')
    else:
        L.append('Open register items cited by at least one live activity, most-blocking first.')
        L.append('')
        L.append('| Item | What | Blocks | Categories | Owner |')
        L.append('|---|---|---|---|---|')
        ref_cat = {r['ref']: cid for cid, _f, _p, _n in feats for r in acts[cid]}
        for b in sorted(blocking, key=lambda x: (-len(blocking[x]), x)):
            rs = blocking[b]
            info = reg.get(b)
            cats = sorted({ref_cat.get(r['ref'], '?') for r in rs})
            refs = ', '.join(r['ref'] for r in rs[:6]) + (' …' if len(rs) > 6 else '')
            what = esc(info['text'])[:80] if info else '**⚠ id not found in any register**'
            L.append('| `%s` | %s | %s | %s | %s |' % (
                b, what, refs, ', '.join(cats), esc(info['owner']) if info else '—'))
    L.append('')
    L.append('---')
    L.append('')

    for cid, front, rel, fn in feats:
        rows = acts[cid]
        L.append('## %s — %s' % (cid, front.get('title', '')))
        L.append('')
        bits = ['%d activit%s' % (len(rows), 'y' if len(rows) == 1 else 'ies'),
                '%d %% done' % pct(rows)]
        ph = front.get('phases') or []
        if ph:
            bits.append('phase %s' % ' · '.join(ph))
        L.append('**%s** · **Story:** [%s](%s)' % (' · '.join(bits), fn, rel))
        if not derived_from_tasks[cid] and rows:
            L.append('  · ⚠ *task files retired — this rolls up the story\'s hand-maintained '
                     'activity table*')
        L.append('')
        if not rows:
            L.append('> This category holds no story by design. It is authored from '
                     'specifications and registers.')
            L.append('')
            continue
        ready = [r for r in rows
                 if r['status'] == 'not-started'
                 and all(d in done_refs for d in r['depends_on'])
                 and not [b for b in r['blocked_by'] if reg.get(b, {}).get('open', True)]]
        L.append('**▶ Ready to start now:** %s' % (
            ', '.join('`%s`' % r['ref'] for r in ready) if ready
            else '*none — every not-started activity here waits on a dependency or a blocker*'))
        L.append('')

    return '\n'.join(L) + '\n', (feats, acts, derived_from_tasks, reg, expected)


def selftest():
    """Render every activity table, parse it back, and assert it round-trips.

    This exists because activities_from_block() shipped reading the STREAMS
    column as the status, so it silently returned nothing - and it is the
    POST-DELETION fallback, meaning the defect would first have surfaced once
    the task files were gone and there was nothing left to re-derive from.

    It seeds from the task files while they exist and from the ON-DISK activity
    tables once they do not. That second path is the point: seeded only from
    load_tasks(), this check went vacuous the moment the task files were deleted
    - it reported "0 activities round-trip" and exited 0, asserting nothing at
    exactly the moment it became the only guard left. A zero total is therefore
    a FAILURE, not a pass.
    """
    feats = load_features()
    tasks = F.load_tasks()
    by_cat = {}
    for t in tasks:
        c = M.categorise(t)[0]
        if c:
            by_cat.setdefault(c, []).append(t)
    seeded = 'task files' if tasks else 'on-disk activity tables'
    bad, n = 0, 0
    for cid, _front, rel, _fn in feats:
        if by_cat.get(cid):
            want = activities_from_tasks(by_cat, cid)
        else:
            want = activities_from_block(F.read(rel))
        if not want:
            continue
        n += len(want)
        got = activities_from_block(render_block(want, cid, bool(tasks), len(want)))
        if len(want) != len(got):
            print('  %s: rendered %d activities, parsed back %d'
                  % (cid, len(want), len(got)))
            bad += 1
            continue
        for a, b in zip(want, got):
            for k in ('ref', 'status'):
                if a[k] != b[k]:
                    print('  %s/%s: %s %r -> %r' % (cid, a['ref'], k, a[k], b[k]))
                    bad += 1
            if [x for x in a['streams'] if x] != b['streams']:
                print('  %s/%s: streams %r -> %r'
                      % (cid, a['ref'], a['streams'], b['streams']))
                bad += 1
            if sorted(a['depends_on']) != sorted(b['depends_on']):
                print('  %s/%s: depends_on %r -> %r'
                      % (cid, a['ref'], a['depends_on'], b['depends_on']))
                bad += 1
            if sorted(a['blocked_by']) != sorted(b['blocked_by']):
                print('  %s/%s: blocked_by %r -> %r'
                      % (cid, a['ref'], a['blocked_by'], b['blocked_by']))
                bad += 1
    # A vacuous selftest is a failed selftest. load_units() is the right
    # denominator: a unit is exactly what becomes an activity, and it resolves to
    # the task files while they exist and to the map afterwards. NOT the map's own
    # row count - that also carries the 13 fileless ids (FW-010-014, 068, 069,
    # N07-N12), which never had a card or a task file and own no activity row.
    want_total = len(F.load_units())
    if n == 0:
        print('build_features: SELFTEST FAILED - parsed 0 activities from the %s.'
              % seeded)
        print('  Nothing was asserted. Either the tables are gone or '
              'parse_activity_block() is broken.')
        return 1
    if want_total and n > want_total:
        print('build_features: SELFTEST FAILED - round-tripped %d activities, the map '
              'absorbed only %d' % (n, want_total))
        return 1
    if want_total and n < want_total:
        # Merging activities downward is legitimate (FW-N17/N18/N19 -> one row);
        # losing them silently is not. Say the number either way.
        print('build_features: NOTE - %d activities for %d units (%d merged or lost)'
              % (n, want_total, want_total - n))
    if bad:
        print('build_features: SELFTEST FAILED - %d mismatch(es) over %d activities'
              % (bad, n))
        return 1
    print('build_features: selftest OK - %d activities round-trip through the block '
          '(seeded from the %s)' % (n, seeded))
    return 0



def main():
    if '--selftest' in sys.argv:
        return selftest()
    body, extra = build()
    if body is None:
        return 1
    feats, acts, derived, reg_all, expected = extra
    check = '--check' in sys.argv
    stale = []

    if F.read(OUT) != body:
        stale.append(OUT)
        if not check:
            path = os.path.join(F.ROOT, OUT)
            tmp = path + '.tmp'
            with open(tmp, 'w', encoding='utf-8', newline='') as fh:
                fh.write(body)
            os.replace(tmp, path)

    for cid, front, rel, fn in feats:
        cur = F.read(rel)
        if BEGIN not in cur or END not in cur:
            print('build_features: %s has no marker block' % rel)
            return 1
        block = render_block(acts[cid], cid, derived[cid], expected.get(cid, 0))
        new = cur.split(BEGIN)[0] + block + cur.split(END, 1)[1]
        if BEGIN_BLK in new and END_BLK in new:
            blk = render_blockers(acts[cid], reg_all)
            new = new.split(BEGIN_BLK)[0] + blk + new.split(END_BLK, 1)[1]
        if new != cur:
            stale.append(rel)
            if not check:
                path = os.path.join(F.ROOT, rel)
                tmp = path + '.tmp'
                with open(tmp, 'w', encoding='utf-8', newline='') as fh:
                    fh.write(new)
                os.replace(tmp, path)

    if check:
        if stale:
            print('build_features: STALE (%d file(s)) - re-run tools/build_features.py'
                  % len(stale))
            for s in stale[:8]:
                print('    %s' % s)
            return 1
        print('build_features: %s and all %d activity tables are current' % (OUT, len(feats)))
        return 0

    n = sum(len(v) for v in acts.values())
    print('build_features: wrote %s (%d activities across %d categories)'
          % (OUT, n, len(feats)))
    if stale:
        print('  updated %d file(s)' % len(stale))
    report_sizes(feats)
    return 0


if __name__ == '__main__':
    sys.exit(main())
